name: buildx

on: [push, pull_request]

jobs:
  armv7-build:
    runs-on: ubuntu-18.04
    name: Build on ubuntu-18.04 armv7
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        id: runcmd
        with:
          arch: armv7
          distro: ubuntu18.04

          # Set an output parameter `uname` for use in subsequent steps
          run: |
            uname -a
            echo ::set-output name=uname::$(uname -a)
            apt update -y
            apt install -y zlib1g zlib1g-dev libffi-dev openssl libssl-dev wget build-essential
            wget https://www.python.org/ftp/python/3.6.5/Python-3.6.5.tgz
            tar xvf Python-3.6.5.tgz
            cd Python-3.6.5
            ./configure --enable-shared --with-ssl
            make -j4
            make install
            cp libpython3.6m.so.1.0 /usr/lib/
            python3 -V
            pip3 install opencv-python==3.4.18.65

      - name: Get the output
        # Echo the `uname` output parameter from the `runcmd` step
        run: |
          echo "The uname output was ${{ steps.runcmd.outputs.uname }}"
